### ISSUE TITLE
[Party Spores] - Terrible FPS lag when party spores are highlighted using Jade

### ISSUE THREAD

**Issue by GanerCodes** [A5ho9999/MinecraftMods#15] opened 2024-07-13 11:03 UTC
**Latest**:
**Latest**:
**1.21**:

Note the FPS on the bottom right
![2024-07-13_06 02 33](https://github.com/user-attachments/assets/5e2e0415-5acf-44da-8e6f-fd5e70b60d58)
![2024-07-13_06 02 42](https://github.com/user-attachments/assets/82a76d9c-58b1-4b13-8936-08c35d4c95c4)

Mods list if relevant
```
blocks_building/
blocks_building/ExpOre-1.21-0.1.jar
blocks_building/PartySpore-1.0.0-1.21.0.jar
blocks_building/arts_and_crafts-fabric-1.21-1.1.5.jar
blocks_building/blockus-2.9.1+1.21.jar
blocks_building/chisel-fabric-1.21-1.8.1.jar
blocks_building/coloredbricks-fabric-1.21-5.2.jar
blocks_building/excavatedvariants-4.3.0-fabric.jar
blocks_building/expandedstorage-14.0.2+1.21-fabric.jar
blocks_building/extshape_blockus-fabric-2.1.4-mc1.21.jar
blocks_building/fabric_wider_ender_chests-1.0.2-1.21.jar
blocks_building/factory_blocks+fabric+1.21-1.3.2.jar
blocks_building/general/
blocks_building/general/extshape-fabric-2.1.4-mc1.21.jar
blocks_building/general/trowel-1.4.0.jar
blocks_building/nicemod-1.4.1 - 1.21.jar
blocks_building/reinforced-barrels-2.5.1+1.21.jar
blocks_building/reinforced-shulker-boxes-3.0.1+1.21.jar
blocks_building/resource_nether_ores-fabric-1.21-2.0.4.jar
gameplay/
gameplay/Iceball-1.3.1+mc1.21.jar
gameplay/do_a_barrel_roll-fabric-3.6.1+1.21.jar
gameplay/forcecrawl-fabric-1.21-1.0.5.jar
gameplay/simple-portal-gun-mc1.21-2.0.0.jar
gameplay/sit-1.21-28.jar
gameplay/tech/
gameplay/tech/led-1.8.3.jar
gameplay/tech/omnihopper-2.3.2+1.21.jar
gameplay/tech/redbits-1.16.6.jar
general/
general/Chunky-1.4.16.jar
general/CommandKeys-Fabric-1.21-2.0.0.jar
general/debugging/
general/debugging/Clumps-fabric-1.21-18.0.0.1.jar
general/debugging/Neruina-2.1.0-fabric+1.21.jar
general/debugging/spark-1.10.73-fabric.jar
general/debugging/wits-1.3.0+1.21-fabric.jar
general/globalpacks-fabric-1.21-21.0.0.jar
general/mod/
general/mod/mod-loading-screen-1.0.4.jar
general/mod/moderate-loading-screen-1.4.2+1.21.jar
general/mod/mods-command-mc1.21-1.1.7.jar
general/preferred-gamerules-1.1.0+1.19.4.jar
general/remember-my-txt-1.0.2+MC1.20.jar
general/render/
general/render/OverlayTweaks 1.21-fabric-1.9.4.jar
general/render/Simple-Block-Overlay 1.21-fabric-1.4.1.jar
general/render/Zoomify-2.14.0+1.21.jar
general/render/freecam-fabric-modrinth-1.3.0-beta1+mc1.21.jar
general/render/modelfix-1.21-1.6-fabric.jar
general/render/motionblur-1.0.5+mc1.21.jar
general/render/perspektive-1.4.0.jar
general/render/show-me-your-skin-1.11.1+1.21.jar
general/render/skin_overrides-2.1.0+1.21.jar
gui/
gui/cleaning/
gui/cleaning/NoRealmsButton-1.1.0-fabric.jar
gui/cleaning/hideexperimentalwarning-1.21.0-1.1.jar
gui/cleaning/no-report-button-fabric-1.6.0.jar
gui/hud+inventory/
gui/hud+inventory/BetterF3-11.0.1-Fabric-1.21.jar
gui/hud+inventory/EffectTimerPlus-Fabric-1.21-2.0.0.jar
gui/hud+inventory/FoodEffectTooltips-1.1.1-1.21.jar
gui/hud+inventory/FuelInfo-2.1+1.21.jar
gui/hud+inventory/Jade-1.21-Fabric-15.1.3.jar
gui/hud+inventory/MouseTweaks-fabric-mc1.21-2.26.jar
gui/hud+inventory/RoughlyEnoughItems-16.0.729-fabric.jar
gui/hud+inventory/componentviewer-fabric-1.1.2+1.21.jar
gui/hud+inventory/inventory-1.9.3.jar
gui/hud+inventory/provihealth-2.1.0+1.21.jar
gui/hud+inventory/showdurability-1.1.1+1.21.0.jar
gui/hud+inventory/shulkerboxtooltip-fabric-5.0.3+1.21.jar
gui/hud+inventory/simple-hud-enhanced+1.21-4.7.0.jar
gui/hud+inventory/tiptapshow-1.6.0+1.21.jar
gui/modmenu-11.0.1.jar
gui/oldmclogo-1.1.3.jar
gui/polymorph-fabric-1.0.2+1.21.jar
gui/reeses_sodium_options-1.7.2+mc1.21.jar
gui/too-many-shortcuts-0.0.3+mc.1.21.jar
gui/toomanybinds-0.3.4+1.20.2.jar
library/
library/ForgeConfigAPIPort-v21.0.1-1.21-Fabric.jar
library/GlitchCore-fabric-1.21-2.0.0.2.jar
library/PuzzlesLib-v21.0.12-1.21-Fabric.jar
library/TerraBlender-fabric-1.21-4.0.0.1.jar
library/YetAnotherConfigLib-3.5.0+1.21-fabric.jar
library/architectury-13.0.4-fabric.jar
library/athena-fabric-1.21-4.0.0.jar
library/azurelib-fabric-1.21-2.3.13.jar
library/brrp-fabric-1.0.3-1.21.jar
library/cicada-lib-0.8.1+1.21-and-above.jar
library/cloth-config-15.0.127-fabric.jar
library/cobweb-fabric-1.21-1.0.0.jar
library/collective-1.21.0-7.70.jar
library/configured-fabric-1.21-2.5.0.jar
library/cupboardfabric-1.21-2.7.jar
library/dynamicassetgenerator-6.1.1-fabric.jar
library/enhancedblockentities-0.10.1+1.21.jar
library/fabric-api-0.100.6+1.21.jar
library/fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
library/ferritecore-7.0.0-fabric.jar
library/fzzy_config-0.3.5+1.21.jar
library/iChunUtil-1.21-Fabric-1.0.0.jar
library/indium-1.0.34+mc1.21.jar
library/mru-0.4.4+1.21.jar
library/owo-lib-0.12.10+1.21.jar
library/particle_core-0.2.3+1.21.jar
library/pneumonocore-1.1.6.jar
library/polymer-bundled-0.9.4+1.21.jar
library/resourcefulconfig-fabric-1.21-3.0.2.jar
library/resourcefullib-fabric-1.21-3.0.9.jar
library/resourcelibrary-fabric-1.21-2.0.2.jar
library/satin-2.0.0.jar
library/sodium-fabric-0.5.11+mc1.21.jar
mobs/
mobs/BetterThanBunnies-1.21-Fabric-1.4.0.jar
mobs/better-babies-0.7.9.jar
mobs/friendsandfoes-fabric-mc1.21-2.0.12.jar
mobs/human-reborn-1.0.8.jar
mobs/snow-pig-4.0.2.jar
mobs/toms_mobs-1.2.6+1.21.jar
mobs/tweaks/
mobs/tweaks/Armorful-3.1.0+1.21.jar
mobs/tweaks/bat-membrane-v.2.1.0.jar
mobs/tweaks/cluckifer-1.0.0+1.21.jar
mobs/tweaks/ironfish-mcmeta-45_1.21.jar
mobs/tweaks/justmobheads-1.21.0-8.1.jar
mobs/tweaks/naturallychargedcreepers-1.21.0-3.4.jar
mobs/tweaks/neutral-animals-1.2.6.jar
mobs/tweaks/randommobsizes-fabric-1.21-2.2.0.jar
mobs/tweaks/yeatthesheep-1.3.jar
optimization/
optimization/general/
optimization/general/fasterrandom-4.1.0.jar
optimization/general/krypton-0.2.8.jar
optimization/general/modernfix-fabric-5.18.7+mc1.21.jar
optimization/general/potatoptimize-0.0.1-dev.6.jar
optimization/render/
optimization/render/ImmediatelyFast-Fabric-1.2.18+1.21.jar
optimization/render/ScalableLux-0.1.0+beta.1+fabric.fc82f44-all.jar
optimization/render/cullleaves-fabric-3.4.0.jar
optimization/render/fastitems-1.0.0-1.21.jar
optimization/render/i-see-you-over-there-1.0.2+1.21.jar
optimization/render/iris-1.7.3+mc1.21.jar
optimization/render/sodium-extra-0.5.7+mc1.21.jar
optimization/server/
optimization/server/c2me-fabric-mc1.21-0.2.0+alpha.11.106.jar
optimization/server/holdthatchunk-2.1.0+1.20.2.jar
optimization/server/letmedespawn-1.3.0.jar
optimization/server/lithium-fabric-mc1.21-0.12.7.jar
optimization/server/noisium-fabric-2.2.1+mc1.21.jar
optimization/server/stutterfix-mc1.21-0.2.2.jar
qol/
qol/BeamBeGone-0.0.2+1.21.jar
qol/NMPR-fabric-1.21-3.0.0.jar
qol/No Increasing Repair Cost-fabric-1.21-1.0.0.jar
qol/OpenYourEye.jar
qol/SlashLength-0.0.1+1.19.3+21.0.jar
qol/accessible-step-mc1.21-1.3.0.jar
qol/azurepaxels-fabric-1.21-1.0.3.jar
qol/bettersafebed-fabric-1.21-16.jar
qol/bottledair-1.21.0-2.3.jar
qol/breakfree-1.3.0.jar
qol/combat/
qol/combat/OldCombatMod-0.1.3.jar
qol/combat/no-shield-delay-1.0.1-beta.jar
qol/combat/old-combat-mod-1.1.1.jar
qol/combat/sharpness-particles-1.0.3+mc1.21.jar
qol/craftable-potion-combinations-1.1.3+1.21.jar
qol/crafting/
qol/crafting/craftable_enchanted_golden_apple-1.0.7.jar
qol/crafting/leatherbundle-2.1.0.jar
qol/crafting/slabstoblocks-1.21-1-fabric.jar
qol/crafting/wooltweaks-1.21.0-3.6.jar
qol/cyclepaintings-1.21.0-3.5.jar
qol/discerning-furnace-1.1.0+MC1.21.jar
qol/door_knocking-1.0.0+1.21-fabric.jar
qol/enchanting_like/
qol/enchanting_like/BowInfinityFix-1.21-fabric-3.1.0.jar
qol/enchanting_like/FallingTree-1.21-1.21.0.6.jar
qol/enchanting_like/fortunate-ancient-debris-2.jar
qol/enchanting_like/general/
qol/enchanting_like/general/EasyAnvils-v21.0.2-1.21-Fabric.jar
qol/enchanting_like/general/EasyMagic-v21.0.1-1.21-Fabric.jar
qol/enchanting_like/merging/
qol/enchanting_like/merging/expanded-armor-enchanting-1.0.8.jar
qol/enchanting_like/merging/expanded-axe-enchanting-1.0.9.jar
qol/enchanting_like/merging/expanded-bow-enchanting-1.1.0.jar
qol/enchanting_like/merging/expanded-crossbow-enchanting-1.0.0.jar
qol/enchanting_like/merging/expanded-trident-enchanting-1.0.9.jar
qol/enchanting_like/merging/expanded-weapon-enchanting-1.0.8.jar
qol/enchanting_like/nofeathertrample-1.21.0-1.2.jar
qol/enchanting_like/sharpness6-1.21-2.jar
qol/enchanting_like/twirl-0.3.3+1.21.jar
qol/enchanting_like/unbreakable-1.21-1.jar
qol/enchanting_like/veinmining-fabric-5.0.0-beta+1.21.jar
qol/extendedbonemeal-1.21.0-3.4.jar
qol/gamemodeoverhaul-fabric-2.2.0+1.21.jar
qol/ghastly-wail-1.2.0+MC1.21.jar
qol/gravestones-1.0.8.jar
qol/inventorytotem-1.21.0-3.2.jar
qol/mergedelytra-1.0.1.jar
qol/mine-enter-5.3.0-beta.1.jar
qol/new_food/
qol/new_food/cookyourfood--mc1.21--fabric--1.12.jar
qol/new_food/goldenberry-fabric-1.21-1.0.0.jar
qol/new_food/nutritiousmilk-1.21.0-3.3.jar
qol/no-teleport-cooldown-1.0.9.jar
qol/nohunger-fabric-1.21-1.3.1.jar
qol/pack-png-painting-mcmeta-42-100_1.21.jar
qol/randombonemealflowers-1.21.0-4.5.jar
qol/removewardeneffect-0.0.2-1.20.5-6.jar
qol/skippy-pearls-1.21.jar
qol/tep-fabric-1.21-1.0.0.jar
qol/tinycoal-fabric-1.21-1.0.2.jar
qol/torch-hit-fabric-1.21-7.0.0.jar
worldgen/
worldgen/biomes/
worldgen/biomes/BiomesOPlenty-fabric-1.21-21.0.0.12.jar
worldgen/biomes/cinderscapes-5.0.1.jar
worldgen/biomes/naturespirit-1.5.5-1.21.jar
worldgen/biomes/terrestria-7.0.0.jar
worldgen/biomes/traverse-8.0.0.jar
worldgen/structures/
worldgen/structures/AdditionalStructures-1.21-(v.5.0.0-fabric).jar
worldgen/structures/HopoBetterMineshaft-[1.21]-1.2.5.jar
worldgen/structures/HopoBetterRuinedPortals-[1.21]-1.4.2.jar
worldgen/structures/Philips-Ruins1.21-1.4[Fabric].jar
worldgen/structures/deadly-deadly-dungeon-1.0.2.1.jar
worldgen/structures/general/
worldgen/structures/general/sparsestructures-fabric-1.21-2.2.0.jar
worldgen/structures/mes-1.3.2-1.21.jar
worldgen/structures/mingen-2.9.jar
worldgen/structures/mns-1.0.2-1.21.jar
worldgen/structures/mss-1.0.2-1.21.jar
worldgen/structures/mvs-4.1.3-1.21.jar
worldgen/structures/panda-temple-V1.jar
worldgen/structures/qraftys-bamboo-villages-2.2.jar
worldgen/structures/qraftys-bunkers-2.2.jar
worldgen/structures/qraftys-halloween-villages-2.2.jar
worldgen/structures/yggdrasil-structure-1.3.0.jar
worldgen/tectonic-fabric-1.21-2.4.0.jar
```

**Comment by A5ho9999** [comment] 2024-07-13 11:19
I will try to look into it on my end, but this seems more like an issue with Jade as well since the issue disappears as soon as the tooltip display is turned off

**Comment by GanerCodes** [comment] 2024-07-13 11:25
Yeah looking at it now i just noticed similar issues happen with other modded blocks; not sure what's causing it

**Comment by A5ho9999** [comment] 2024-07-13 11:55
This should be fixed on my end in https://modrinth.com/mod/party-spores/version/1.0.1-1.21.0

Thanks for the report

**Closed by A5ho9999** 2024-07-13 11:55 UTC
Labels: Investigating, Priority: Normal, Confirmed

**Comment by GanerCodes** [comment] 2024-07-13 12:38
Awesome, thank you! what'd you do to fix it [ive noticed the same issue on other mods]?

**Comment by A5ho9999** [comment] 2024-07-13 12:42
For me, the issue is related to https://github.com/Snownee/Jade/blob/0afef33c022393aedfd9315aa7f4f2e0d685266f/src/main/java/snownee/jade/overlay/RayTracing.java#L216 mainly the pickBlock method change in 1.21. I simply removed a part that wasn't needed but will put in by default by most devs.
